### ISSUE TITLE
Remove optimizer.py and replace it using Hydra instantiate

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#404]
Currently we use "load_optimizer" and "get_optimizer" from bliss/optimizer.py in quite a few places, but it doesn't seem to do much.

We already eliminated the separate config files for the optimizer in #396. Currently we specify "training.optimizer" as a dictionary:
https://github.com/prob-ml/bliss/blob/71393515625d821b9b250c7186ba8fba6c808759/config/training/sdss_galaxy_encoder.yaml#L9-L17

This could be made even simpler as follows:
```
 training: 
     name: "sdss_galaxy_encoder" 
     model: ${models.galaxy_encoder} 
     dataset: ${datasets.simulated} 
     optimizer: 
         _target_: torch.optimizers.Adam
         lr: 1e-4 
         weight_decay: 0 
```
