### ISSUE TITLE
caching pip and git-lfs in CI

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#62]
It might be nice to cache pip installation in the CI with like: 

```
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
```

but I got inconsistent runs (sometimes taking longer than just installing) so more investigation is needed. It also caused an error for me in at least one test run 

Also caching `git-lfs` might give us even more speed up: https://github.com/actions/checkout/issues/165
but havent' tried it out yet.
